"""added image path

Revision ID: 01ecdeae6406
Revises: 55fb87da818d
Create Date: 2023-11-16 21:28:57.052472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ecdeae6406'
down_revision: Union[str, None] = '55fb87da818d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'image_path')
    # ### end Alembic commands ###
