"""Trying to Add Image

Revision ID: 27be978c986b
Revises: 01ecdeae6406
Create Date: 2023-11-17 21:37:27.723181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27be978c986b'
down_revision: Union[str, None] = '01ecdeae6406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('Users', sa.Column('mime', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('Users', sa.Column('ext', sa.String(), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'ext')
    op.drop_column('Users', 'mime')
    op.drop_column('Users', 'size')
    # ### end Alembic commands ###
